[features]
seeds = true

[programs.devnet]
prediction_market = "HhbBippsA7ETvNMNwBbY7Fg8B24DzgJ3nENetYPwR9bQ"

[provider]
cluster = "devnet"
wallet  = "~/.config/solana/id.json"

[toolchain]
anchor_version = "0.31.1"

[build]
rust = true